/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: schema.json
export type SocialLink = {
  _id: string;
  _type: 'socialLink';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  platform?: 'facebook' | 'instagram' | 'email';
  url?: string;
};

export type SanityFileAssetReference = {
  _ref: string;
  _type: 'reference';
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: 'sanity.fileAsset';
};

export type Newsletter = {
  _id: string;
  _type: 'newsletter';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  pdf?: {
    asset?: SanityFileAssetReference;
    media?: unknown;
    _type: 'file';
  };
};

export type LocalResources = {
  _id: string;
  _type: 'localResources';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  topic?: string;
  resources?: Array<{
    text?: string;
    link?: string;
    _key: string;
  }>;
};

export type SanityImageAssetReference = {
  _ref: string;
  _type: 'reference';
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: 'sanity.imageAsset';
};

export type GalleryEvent = {
  _id: string;
  _type: 'galleryEvent';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  image?: Array<{
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: 'image';
    _key: string;
  }>;
  desc?: string;
};

export type SanityImageCrop = {
  _type: 'sanity.imageCrop';
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityImageHotspot = {
  _type: 'sanity.imageHotspot';
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type Event = {
  _id: string;
  _type: 'event';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  date?: string;
  time?: string;
  desc?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: 'span';
      _key: string;
    }>;
    style?: 'normal' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'blockquote';
    listItem?: 'bullet' | 'number';
    markDefs?: Array<{
      href?: string;
      _type: 'link';
      _key: string;
    }>;
    level?: number;
    _type: 'block';
    _key: string;
  }>;
};

export type SanityImagePaletteSwatch = {
  _type: 'sanity.imagePaletteSwatch';
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: 'sanity.imagePalette';
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: 'sanity.imageDimensions';
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityImageMetadata = {
  _type: 'sanity.imageMetadata';
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: 'sanity.fileAsset';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: 'sanity.assetSourceData';
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: 'sanity.imageAsset';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: 'geopoint';
  lat?: number;
  lng?: number;
  alt?: number;
};

export type Slug = {
  _type: 'slug';
  current?: string;
  source?: string;
};

export type AllSanitySchemaTypes =
  | SocialLink
  | SanityFileAssetReference
  | Newsletter
  | LocalResources
  | SanityImageAssetReference
  | GalleryEvent
  | SanityImageCrop
  | SanityImageHotspot
  | Event
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint
  | Slug;

// Source: ../src/utils/sanity.ts
// Variable: UPCOMING_EVENTS_QUERY
// Query: *[_type == "event"] | order(date asc, _id asc) {    _id,    title,    date,    time,    desc  }
export type UPCOMING_EVENTS_QUERY_RESULT = Array<{
  _id: string;
  title: string | null;
  date: string | null;
  time: string | null;
  desc: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: 'span';
      _key: string;
    }>;
    style?: 'blockquote' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'normal';
    listItem?: 'bullet' | 'number';
    markDefs?: Array<{
      href?: string;
      _type: 'link';
      _key: string;
    }>;
    level?: number;
    _type: 'block';
    _key: string;
  }> | null;
}>;

// Source: ../src/utils/sanity.ts
// Variable: GALLERY_EVENTS_QUERY
// Query: *[_type == "galleryEvent"] | order(_createdAt desc, _id asc) {    _id,    title,    image,    desc  }
export type GALLERY_EVENTS_QUERY_RESULT = Array<{
  _id: string;
  title: string | null;
  image: Array<{
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: 'image';
    _key: string;
  }> | null;
  desc: string | null;
}>;

// Source: ../src/utils/sanity.ts
// Variable: LOCAL_RESOURCES_QUERY
// Query: *[_type == "localResources"] | order(topic asc, _id asc) {    _id,    topic,    resources[]{      text,      link    }  }
export type LOCAL_RESOURCES_QUERY_RESULT = Array<{
  _id: string;
  topic: string | null;
  resources: Array<{
    text: string | null;
    link: string | null;
  }> | null;
}>;

// Source: ../src/utils/sanity.ts
// Variable: NEWSLETTERS_QUERY
// Query: *[_type == "newsletter"] | order(title asc, _id asc) {    _id,    title,    pdf  }
export type NEWSLETTERS_QUERY_RESULT = Array<{
  _id: string;
  title: string | null;
  pdf: {
    asset?: SanityFileAssetReference;
    media?: unknown;
    _type: 'file';
  } | null;
}>;

// Source: ../src/utils/sanity.ts
// Variable: SOCIAL_LINKS_QUERY
// Query: *[_type == "socialLink"] | order(platform asc, _id asc) {    _id,    platform,    url  }
export type SOCIAL_LINKS_QUERY_RESULT = Array<{
  _id: string;
  platform: 'email' | 'facebook' | 'instagram' | null;
  url: string | null;
}>;

// Query TypeMap
import '@sanity/client';
declare module '@sanity/client' {
  interface SanityQueries {
    '\n  *[_type == "event"] | order(date asc, _id asc) {\n    _id,\n    title,\n    date,\n    time,\n    desc\n  }\n': UPCOMING_EVENTS_QUERY_RESULT;
    '\n  *[_type == "galleryEvent"] | order(_createdAt desc, _id asc) {\n    _id,\n    title,\n    image,\n    desc\n  }\n': GALLERY_EVENTS_QUERY_RESULT;
    '\n  *[_type == "localResources"] | order(topic asc, _id asc) {\n    _id,\n    topic,\n    resources[]{\n      text,\n      link\n    }\n  }\n': LOCAL_RESOURCES_QUERY_RESULT;
    '\n  *[_type == "newsletter"] | order(title asc, _id asc) {\n    _id,\n    title,\n    pdf\n  }\n': NEWSLETTERS_QUERY_RESULT;
    '\n  *[_type == "socialLink"] | order(platform asc, _id asc) {\n    _id,\n    platform,\n    url\n  }\n': SOCIAL_LINKS_QUERY_RESULT;
  }
}
